application:
  port: 8000
  host: 127.0.0.1
database:
  host: 127.0.0.1
  username: wangjian
  password: 123456
  port: 5432
  database_name: actix_demo
email_client:
  base_url: https://api.postmarkapp.com
  sender_email: wangjian0504@gmail.com
  authorization_token: 123456
  timeout_milliseconds: 10000
